blank_issues_enabled: false
contact_links:
  - name: Serveur Discord
    url: https://discord.gg/RGRq9kwQx8
    about: Si vous avez des doutes, des questions, ou simplement pour passer du temps, c'est par ici!
  - name: Formulaire de recrutement
    url: https://forms.gle/epR5om7t57KYkUha7
    about: Envie de rejoindre l'équipe? Postulez ici!
